---
# tasks file for jdk
- name: get jdk1.8
  get_url:
    url: "http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz"
    dest: /opt/jdk1.8.tar.gz
    validate_certs: no
    headers: "Cookie: oraclelicense=accept-securebackup-cookie"

- name: create path
  file:
    path: /opt/jdk1.8
    state: directory

- name: unpack the archive
  unarchive:
    remote_src: yes
    src: /opt/jdk1.8.tar.gz
    dest: /opt/jdk1.8
    owner: root
    group: root
    extra_opts:
    - --strip-components=1
