---
# tasks file for tomcat

- name: TOMCAT USER CREATION
  user:
   name: tomcat
   createhome: yes
   home: /opt/tomcat

- name: TOMCAT REPOSITORY CREATION
  file:
   path: /opt/tomcat
   state: directory

- name: TOMCAT DOWNLOAD & UNARCHIVING
  unarchive:
   src: http://mirrors.ircam.fr/pub/apache/tomcat/tomcat-9/v9.0.12/bin/apache-tomcat-9.0.12.tar.gz
   dest: /opt/tomcat
   owner: tomcat
   group: tomcat
   extra_opts:
    - --strip-components=1 
   remote_src: yes

- name: TOMCAT SERVICE CREATION
  copy:
   src: tomcat.service
   dest: /etc/systemd/system/tomcat.service
  notify:
   - daemon-reload

- name: TOMCAT RESTARTING
  systemd:
   name: tomcat
   state: restarted
   daemon_reload: yes
   enabled: yes
